name: Run and Deploy Python Scripts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Step 4: Run the Python scripts
      - name: Run 01.py
        run: |
          python scripts/01.py
      - name: Run 02.py
        run: |
          python scripts/02.py
      - name: Run 03.py
        run: |
          python scripts/03.py

      # Step 5: Move output files to docs folder for GitHub Pages
      - name: Move output files to docs folder
        run: |
          mv output_file.html docs/index.html  # Adjust this if your artifact isn't an HTML file

      # Step 6: Commit changes to docs folder
      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/
          git commit -m "Deploy artifacts to docs folder"
          git push origin main
