name: Run and Deploy Python Scripts to gh-pages

on:
  push:
    branches:
      - main

jobs:
  run-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run 01.py
        run: python script/01.py

      - name: Run 02.py
        run: python script/02.py

      - name: Run 03.py
        run: python script/03.py

      - name: Disable Jekyll
        run: touch .nojekyll  # At the root, not in a docs/ folder

      - name: List files for verification
        run: ls -l  # List files at the root, should include index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Use root directory
          publish_branch: gh-pages
          keep_files: true
