name: Run Python Scripts

# Trigger workflow on push or pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use any Python 3.x version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Step 4: Run the Python scripts
      - name: Run 01.py
        run: |
          python scripts/01.py
      - name: Run 02.py
        run: |
          python scripts/02.py
      - name: Run 03.py
        run: |
          python scripts/03.py

      # Step 5: Upload artifacts (output files) to main directory
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: output-files
          path: ./  # Save all generated artifacts in the main directory

