name: Run and Deploy Python Scripts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Step 4: Run the first Python script (01.py)
      - name: Run 01.py
        run: python script/01.py

      # Step 5: Run the second Python script (02.py)
      - name: Run 02.py
        run: python script/02.py

      # Step 6: Run the third Python script (03.py) to generate the map
      - name: Run 03.py
        run: python script/03.py

      # Step 7: Ensure the docs directory exists
      - name: Create docs directory if not exists
        run: mkdir -p docs

      # Step 8: Move the generated index.html to docs folder
      - name: Move index.html to docs
        run: mv index.html docs/index.html

      # Step 9: Commit and push changes to docs folder
      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/
          git commit -m "Deploy index.html to docs folder"
          git push origin main

      # Step 10: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
